mhamzaraja/Recruiter-Agency-Frontend

src/app/app-routing.module.ts
src/app/components/pages/about/about.component.html
src/app/components/pages/about/about.component.ts
src/app/components/pages/about/about.service.ts
src/app/components/pages/dashboard/dashboard.component.html
src/app/components/pages/home-one/home-one.component.html
src/app/components/pages/home-one/home-one.component.ts
src/app/components/pages/home-one/home-one.service.ts
src/app/components/pages/home-three/home-three.component.html
src/app/components/pages/home-three/home-three.component.ts
src/app/components/pages/home-three/home-three.service.ts
src/app/components/pages/home-two/home-two.component.html
src/app/components/pages/home-two/home-two.component.ts
src/app/components/pages/home-two/home-two.service.ts
src/app/components/pages/jobs/jobs.component.html
src/app/components/pages/jobs/jobs.component.ts

Pagination Api Done, Data Analytics Api done on About and All three Home Pages, Also Check Some Routing issues

Pagination Api, DataAnalystics Api Done

---

src/app/app-routing.module.ts
src/app/components/pages/jobs/jobs.component.html
src/app/components/pages/jobs/jobs.component.ts
src/app/components/pages/jobs/services/jobs.service.ts
src/app/components/pages/post-a-job/post-a-job.component.ts

Some API issues need to be fix

fix routing, some issues to be fixed

---

src/app/app-routing.module.ts
src/app/components/pages/favourite-jobs/favourite-jobs.component.html
src/app/components/pages/favourite-jobs/favourite-jobs.component.ts
src/app/components/pages/favourite-jobs/services/favourite.service.ts
src/app/components/pages/jobs/jobs.component.html
src/app/components/pages/jobs/jobs.component.scss
src/app/components/pages/jobs/jobs.component.ts
src/app/components/pages/jobs/services/jobs.service.ts

Routing fixed, Add, Get and Delete Favourite Jobs

Feature zafar 12 09 22

---

src/app/components/pages/favourite-jobs/favourite-jobs.component.ts
src/app/components/pages/favourite-jobs/services/favourite.service.ts
src/app/components/pages/jobs/jobs.component.html
src/app/components/pages/jobs/jobs.component.ts
src/app/components/pages/jobs/services/jobs.service.ts

add to favourites and remove from favourites

add to favourites and remove from favourites

---

src/app/components/pages/candidates-details/candidates-details.component.html
src/app/components/pages/candidates-details/candidates-details.component.ts
src/app/components/pages/candidates-details/services/camdidates-details.service.ts
src/app/components/pages/candidates/candidates.component.html
src/app/components/pages/candidates/candidates.component.ts
src/app/components/pages/candidates/services/candidates.service.ts

Get all candidates and candidates details

get all candidates and candidates details

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/common/navbar-style-one/navbar-style-one.component.html
src/app/components/common/navbar-style-one/navbar-style-one.component.ts
src/app/components/common/navbar-style-three/navbar-style-three.component.html
src/app/components/common/navbar-style-three/navbar-style-three.component.ts
src/app/components/common/navbar-style-two/navbar-style-two.component.html
src/app/components/common/navbar-style-two/navbar-style-two.component.ts
src/app/components/guards/auth.guard.ts
src/app/components/guards/loggedin.guard.spec.ts
src/app/components/guards/loggedin.guard.ts
src/app/components/guards/services/auth.service.ts
src/app/components/pages/login/login.component.ts
src/styles.scss

All ROuting Problems are Fixed, nav bar issues fixed, logged in and try to access the login page issue fixed.

Routing Fixed Completely

---

src/app/components/pages/employers/employers.component.html
src/app/components/pages/employers/employers.component.ts
src/app/components/pages/employers/services/employer.service.spec.ts
src/app/components/pages/employers/services/employer.service.ts

Get all employers at Admin dashboard

get all employers at admin dashboard

---

src/app/components/pages/candidates-details/candidates-details.component.html
src/app/components/pages/employer-dashboard/dashboard.component.html
src/app/components/pages/employer-dashboard/dashboard.component.ts
src/app/components/pages/employer-dashboard/services/dashboard.service.ts
src/app/components/pages/register/register.component.html
src/styles.scss

Add employer register button ,fix employer profile on dashboard

Add emp reg button ,fix employr profile on dshbord

---

src/app/app-routing.module.ts
src/app/components/pages/candidates/candidates.component.html
src/app/components/pages/employer-dashboard/dashboard.component.html
src/app/components/pages/employer-dashboard/dashboard.component.ts
src/app/components/pages/employer-dashboard/services/dashboard.service.ts
src/app/components/pages/employers-register/employers-register.component.html
src/app/components/pages/employers-register/employers-register.component.ts
src/app/components/pages/employers-register/services/employers-register.service.ts
src/app/components/pages/employers/employers.component.html
src/app/components/pages/jobs/jobs.component.html
src/app/components/pages/jobs/jobs.component.ts
src/app/components/pages/jobs/services/jobs.service.ts
src/app/components/pages/login/login.component.scss
src/app/components/pages/register/register.component.html
src/styles.scss

Apply the posted job API for specific users,
Create the Employer Signup component and Apply its API,
Apply the Checks that Favourites Jobs icon shows only to candidate

Fixing shahzor 21 09 2022

---

src/app/components/pages/employer-dashboard/dashboard.component.html
src/app/components/pages/employer-dashboard/dashboard.component.scss
src/app/components/pages/employer-dashboard/dashboard.component.ts
src/app/components/pages/employer-dashboard/services/dashboard.service.ts
src/app/components/pages/post-a-job/post-a-job.component.ts

Update Job Information

---

src/app/components/pages/employer-dashboard/dashboard.component.html
src/app/components/pages/employer-dashboard/dashboard.component.scss
src/app/components/pages/employer-dashboard/dashboard.component.ts
src/app/components/pages/employer-dashboard/services/dashboard.service.ts
src/app/components/pages/post-a-job/post-a-job.component.html
src/app/components/pages/post-a-job/post-a-job.component.ts
src/app/components/pages/post-a-job/services/post-a-job.service.ts

Apply Delete job API

---

src/app/components/common/navbar-style-one/navbar-style-one.component.html
src/app/components/pages/dashboard/basic-info/basic-info.component.html
src/app/components/pages/dashboard/basic-info/basic-info.component.ts
src/app/components/pages/dashboard/basic-info/services/basic-info.service.ts
src/app/components/pages/dashboard/education/education.component.html
src/app/components/pages/dashboard/education/education.component.ts
src/app/components/pages/dashboard/experience/experience.component.html
src/app/components/pages/dashboard/experience/experience.component.ts
src/app/components/pages/dashboard/project/project.component.html
src/app/components/pages/dashboard/project/project.component.ts
src/app/components/pages/dashboard/project/services/project.service.ts
src/app/components/pages/dashboard/skills-languages/skills-languages.component.html
src/app/components/pages/dashboard/skills-languages/skills-languages.component.ts
src/app/components/pages/employer-dashboard/services/dashboard.service.ts
src/styles.scss

convert the create and update forms of all components of candidate dashboard,
fix some validation issues of the skill and language component

convt all update and create form of cand dash comp

---

src/app/components/pages/employer-dashboard/dashboard.component.html
src/app/components/pages/employer-dashboard/dashboard.component.ts
src/app/components/pages/post-a-job/post-a-job.component.html

Add delete jobs option in modal box

add delete jobs option in modal box

---

src/app/components/common/services/navbar.service.ts
src/app/components/config/userToken.ts
src/app/components/pages/dashboard/dashboard.component.ts
src/app/components/pages/dashboard/education/services/education.service.ts
src/app/components/pages/dashboard/experience/services/experience.service.ts
src/app/components/pages/dashboard/project/services/project.service.ts
src/app/components/pages/dashboard/services/dashboard.service.ts
src/app/components/pages/dashboard/skills-languages/services/skills-languages.service.ts
src/app/components/pages/employer-dashboard/dashboard.component.ts

set the id in the local storage
and set all the candidate dashboard getall apis

Fix all the Candidate Dash getAll APis

---

src/app/components/pages/dashboard/education/services/education.service.ts
src/app/components/pages/dashboard/experience/services/experience.service.ts
src/app/components/pages/dashboard/project/services/project.service.ts
src/app/components/pages/dashboard/skills-languages/services/skills-languages.service.ts
src/app/components/pages/favourite-jobs/favourite-jobs.component.html
src/app/components/pages/jobs/jobs.component.html

Some fixes in candidate dashboard

Some fixes in candidate dashboard

---

src/app/components/pages/resume-details/services/resume.service.ts

Some fixes in resume service.ts

Some fixes in resume service.ts

---

src/app/components/pages/dashboard/basic-info/basic-info.component.ts
src/app/components/pages/dashboard/basic-info/services/basic-info.service.ts
src/app/components/pages/dashboard/education/services/education.service.ts
src/app/components/pages/dashboard/experience/services/experience.service.ts
src/app/components/pages/dashboard/project/services/project.service.ts
src/app/components/pages/dashboard/skills-languages/services/skills-languages.service.ts

Fixes in candidates dashboard

---

src/app/components/pages/dashboard/basic-info/basic-info.component.html
src/app/components/pages/dashboard/education/education.component.ts
src/app/components/pages/dashboard/experience/experience.component.ts
src/app/components/pages/dashboard/experience/services/experience.service.ts
src/app/components/pages/dashboard/project/project.component.ts
src/app/components/pages/dashboard/project/services/project.service.ts

Api fixes in candidate dashboard child components

Api fixes in candidate dashboard child components

---

src/app/components/pages/dashboard/basic-info/basic-info.component.ts
src/app/components/pages/dashboard/basic-info/services/basic-info.service.ts
src/app/components/pages/dashboard/education/education.component.ts
src/app/components/pages/dashboard/education/services/education.service.ts
src/app/components/pages/dashboard/experience/experience.component.ts
src/app/components/pages/dashboard/experience/services/experience.service.ts
src/app/components/pages/dashboard/project/project.component.ts
src/app/components/pages/dashboard/project/services/project.service.ts
src/app/components/pages/dashboard/skills-languages/services/skills-languages.service.ts
src/app/components/pages/dashboard/skills-languages/skills-languages.component.ts

All Apis of Cand Dashboard set completely,
All Apis CRUD of Cand Dashboard

All Apis of Cand Dashboard set completely

---

src/app/components/pages/admin-dashboard/jobs-applications/jobs-applications.component.html
src/app/components/pages/dashboard/education/education.component.ts
src/app/components/pages/dashboard/experience/experience.component.ts
src/app/components/pages/dashboard/project/project.component.ts
src/app/components/pages/employer-dashboard/services/dashboard.service.ts
src/app/components/pages/resume-details/resume-details.component.ts
src/app/components/pages/resume-details/services/resume.service.ts

employer set completely

---

src/app/components/pages/admin-dashboard/candidates/candidates.component.ts
src/app/components/pages/admin-dashboard/candidates/services/candidates.service.ts
src/app/components/pages/admin-dashboard/professionals/professionals.component.ts
src/app/components/pages/admin-dashboard/professionals/services/professionals.service.ts
src/app/components/pages/dashboard/dashboard.component.ts

fixes in delete API's of emp and cand on admin dashboard

fixes in delete api's of emp and cand on admin d

---

src/app/components/pages/companys/companyList/companyList.component.html
src/app/components/pages/dashboard/education/education.component.html
src/app/components/pages/dashboard/education/education.component.ts
src/app/components/pages/dashboard/experience/experience.component.html
src/app/components/pages/dashboard/experience/experience.component.ts
src/app/components/pages/dashboard/project/project.component.html
src/app/components/pages/dashboard/project/project.component.ts
src/app/components/pages/dashboard/skills-languages/skills-languages.component.html
src/app/components/pages/dashboard/skills-languages/skills-languages.component.ts
src/app/components/pages/favourite-jobs/favourite-jobs.component.html
src/app/components/pages/favourite-jobs/favourite-jobs.component.ts

1. Add modal service in the candidate dashboard component's delete button
2. Some fixes in the favorite job's component

Add modl service in cndidate dshbrd comp dlete opt

---

src/app/components/pages/admin-dashboard/admin-dashboard.component.html
src/app/components/pages/candidates/candidates.component.html
src/app/components/pages/candidates/candidates.component.scss
src/app/components/pages/candidates/candidates.component.ts
src/app/components/pages/candidates/services/candidates.service.ts

- Make a table for all candidates table in the candidate component
- Add resume modal service in the candidate component
- Add resume button in cand table
- Active delete candidate button only for admin

Add resume modal in candidate table and some fixes
